---

seed: 42

dataset:
  name: celeba
  train_file_path: ./datasets/celeba/meta/trainset_100.txt
  test_file_path: ./datasets/celeba/meta/testset_100.txt
  img_path: /home/comp/csxpeng/code/56914551/attack_datasets/CelebA_new/img_align_celeba
  validation_set_size: 0
  crop_size: 108
  image_size: 64
  batch_size: 64
  offset_height: 55
  offset_width: 35
  sampler: false

