---
seed: 42

model:
  architecture: VGG16
  num_classes: 1000
  pretrained: true
  # (if finetune on some model, set resume_path)
  resume_path: ./checkpoints/target_model/target_ckp/VGG16_88.26.tar

dataset:
  name: celeba
  train_file_path: ./datasets/celeba/meta/trainset.txt
  test_file_path: ./datasets/celeba/meta/testset.txt
  gan_file_path: ./datasets/celeba/meta/ganset.txt
  img_path: ./data/celeba/img_align_celeba
  validation_set_size: 0
  transformations:
    crop_size: 108
    image_size: 64
    offset_height: 55
    offset_width: 35

transformations:
  ToPILImage: {}
  Resize:
    size: [64, 64]
  RandomHorizontalFlip:
    p: 0.5
  
optimizer:
  SGD:
    lr: 0.01
    momentum: 0.9
    weight_decay: 0.0001

lr_scheduler:
  MultiStepLR:
    milestones: [70, 90]
    gamma: 0.2

training:
  num_epochs: 100
  batch_size: 64
  dataloader_num_workers: 2
  save_path: results
