---

stylegan_model: stylegan2-ada-pytorch/ffhq.pkl
seed: 2026
dataset: celeba_identities

target_model:
  architecture: densenet121
  num_classes: 1000
  weights: ./results/densenet121_celeba/Classifier_0.9131.pth

evaluation_model:
  architecture: inception
  num_classes: 1000
  weights: ./results/inceptionv3_celeba/Classifier_0.9487.pth

candidates:
  num_candidates: 100
  candidate_search:
    search_space_size: 2000
    center_crop: 800
    resize: 224
    horizontal_flip: true
    batch_size: 25
    truncation_psi: 0.5
    truncation_cutoff: 8

attack:
  batch_size: 35
  num_epochs: 70
  targets: 0-100
  discriminator_loss_weight: 0.0
  single_w: true
  clip: false
  transformations:
    CenterCrop:
      size: 800
    Resize:
      size: 224
      antialias: true

  optimizer:
    Adam:
      lr: 0.005
      weight_decay: 0
      betas: [ 0.1, 0.1 ]

final_selection:
  samples_per_target: 100
  approach: transforms
  iterations: 100


wandb:
  enable_logging: true
  wandb_init_args:
    project: model_inversion_attacks
    save_code: true
    name: Attack_CelebA_FFHQ

